import Footer from '@/components/Footer';
import Header from '@/components/Header';
import { Providers } from '@/components/Provider';
import '@/globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next ',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className="antialiased bg-zinc-50 dark:bg-black">
        <Providers>
          <Header />
          <main className="mb-auto">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
